title: WHO IS RITIKA SINGH??
author: Ritika Singh
email: ritika2002singh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GROWING DAY BY DAY!
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  RitikaSingh02 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
